version: '3.8'

services:
  postgres-db:
    image: postgres:17.4
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  invoices-backend:
    build: .
    container_name: invoices-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_FLYWAY_ENABLED: "false"
    depends_on:
      - postgres-db

  invoices-frontend:
    build: ./Frontend
    container_name: invoices-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - invoices-backend