spring.application.name=Invoices-Stripe

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
logging.level.root=INFO
#logging.level.mk.ukim.finki.eshopbackend=DEBUG
logging.level.org.springframework=WARN

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kostadinovtrajce3@gmail.com
spring.mail.password=vfsftiyklknzkxcu    
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.profiles.active=dev
spring.h2.console.enabled=false