spring.datasource.url=jdbc:postgresql://localhost:5433/InvoicesDB
spring.datasource.username=invoices
spring.datasource.password=invoices

spring.jpa.hibernate.ddl-auto=validate

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE