spring.application.name=Invoices-Stripe

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
logging.level.root=INFO
#logging.level.mk.ukim.finki.eshopbackend=DEBUG
logging.level.org.springframework=WARN

spring.profiles.active=dev
spring.h2.console.enabled=false